# 端口
server:
  # todo：修改为当前项目端口
  # 测试/前端调用
#  port: 8078
  # 开发
  port: 8079

# 请求前缀  todo：视情况修改
api:
  prefix:
    global: /api

# mybatis mapper locations
mybatis:
  mapper-locations: classpath:mapper/*.xml

# active which profile
spring:
  profiles:
    active: dev

# log method
logging:
  file: logs/demo.log
  level:
    com:
      zxtnet:
        # todo：修改成对应目录
        template: debug
